{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spaceops.serviceAccountName" . }}
  namespace: {{ include "spaceops.namespace" . }}
  labels:
    {{- include "spaceops.labels" . | nindent 4 }}
{{- end }}
