#!/usr/bin/env python3
"""Render Kustomize ConfigMap for ops-config/ (Argo CD sync after agent PR merge)."""

from __future__ import annotations

import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OPS_CONFIG = REPO_ROOT / "ops-config"
OUT_DIR = REPO_ROOT / "deploy" / "gitops" / "ops-config-kustomize"
HEADER = """# Generated by scripts/render_ops_config_kustomize.py — do not edit by hand.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spaceops-stage
configMapGenerator:
  - name: spaceops-ops-config
    options:
      disableNameSuffixHash: true
    files:
"""


def collect_yaml_files() -> list[Path]:
    if not OPS_CONFIG.is_dir():
        raise SystemExit(f"Missing {OPS_CONFIG}")
    files = sorted(
        p
        for p in OPS_CONFIG.rglob("*.yaml")
        if p.is_file() and p.name != "kustomization.yaml"
    )
    if not files:
        raise SystemExit(f"No YAML files under {OPS_CONFIG}")
    return files


def render(*, check: bool) -> None:
    lines = [HEADER]
    for path in collect_yaml_files():
        rel = path.relative_to(OPS_CONFIG).as_posix()
        repo_rel = f"../../../ops-config/{rel}"
        lines.append(f"      - {repo_rel}\n")
    content = "".join(lines)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / "kustomization.yaml"
    if check and out_path.is_file() and out_path.read_text(encoding="utf-8") == content:
        print(f"OK: {out_path.relative_to(REPO_ROOT)} up to date")
        return
    if check and out_path.is_file():
        raise SystemExit(
            f"{out_path.relative_to(REPO_ROOT)} is stale — run: python scripts/render_ops_config_kustomize.py"
        )
    out_path.write_text(content, encoding="utf-8")
    print(
        f"Wrote {out_path.relative_to(REPO_ROOT)} ({len(collect_yaml_files())} files)"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Render ops-config Kustomize for Argo CD"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if kustomization.yaml would change",
    )
    args = parser.parse_args()
    render(check=args.check)


if __name__ == "__main__":
    main()
