#!/usr/bin/env python3
"""Render Kustomize ConfigMap for ops-config/ (Argo CD — paths must stay under kustomize root)."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OPS_CONFIG = REPO_ROOT / "ops-config"
OUT_DIR = REPO_ROOT / "deploy" / "gitops" / "ops-config-kustomize"
FILES_DIR = OUT_DIR / "files"
HELM_VALUES = (
    REPO_ROOT / "deploy" / "helm" / "spaceops" / "values-ops-config-mounts.yaml"
)
HEADER = """# Generated by scripts/render_ops_config_kustomize.py — do not edit by hand.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spaceops-stage
configMapGenerator:
  - name: spaceops-ops-config
    options:
      disableNameSuffixHash: true
    files:
"""

MOUNTS_HEADER = """# Generated by scripts/render_ops_config_kustomize.py — do not edit by hand.
# ConfigMap keys must be flat (no '/'); Helm maps keys -> subpaths under /app/ops-config.
api:
  persistence:
    opsConfig:
      configMapItems:
"""


def configmap_key(rel: Path) -> str:
    """Kubernetes ConfigMap data keys: alphanumeric, '-', '_', '.' only."""
    return rel.as_posix().replace("/", ".")


def collect_yaml_files() -> list[Path]:
    if not OPS_CONFIG.is_dir():
        raise SystemExit(f"Missing {OPS_CONFIG}")
    files = sorted(
        p
        for p in OPS_CONFIG.rglob("*.yaml")
        if p.is_file() and p.name != "kustomization.yaml"
    )
    if not files:
        raise SystemExit(f"No YAML files under {OPS_CONFIG}")
    return files


def render(*, check: bool) -> None:
    yaml_files = collect_yaml_files()
    if FILES_DIR.exists():
        shutil.rmtree(FILES_DIR)
    FILES_DIR.mkdir(parents=True, exist_ok=True)

    lines = [HEADER]
    mount_lines = [MOUNTS_HEADER]
    for src in yaml_files:
        rel = src.relative_to(OPS_CONFIG)
        dest = FILES_DIR / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        cm_key = configmap_key(rel)
        cm_path = (Path("files") / rel).as_posix()
        lines.append(f"      - {cm_key}={cm_path}\n")
        mount_lines.append(
            f"        - key: {cm_key}\n" f"          path: {rel.as_posix()}\n"
        )

    content = "".join(lines)
    mounts_content = "".join(mount_lines)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / "kustomization.yaml"
    mounts_stale = (
        not HELM_VALUES.is_file()
        or HELM_VALUES.read_text(encoding="utf-8") != mounts_content
    )
    if (
        check
        and out_path.is_file()
        and out_path.read_text(encoding="utf-8") == content
        and not mounts_stale
    ):
        # Also verify copied files match sources.
        stale = False
        for src in yaml_files:
            rel = src.relative_to(OPS_CONFIG)
            dest = FILES_DIR / rel
            if not dest.is_file() or dest.read_bytes() != src.read_bytes():
                stale = True
                break
        if not stale:
            print(
                f"OK: {out_path.relative_to(REPO_ROOT)} up to date ({len(yaml_files)} files)"
            )
            return
    if check and (out_path.is_file() or HELM_VALUES.is_file()):
        raise SystemExit(
            "ops-config render output is stale — run: python scripts/render_ops_config_kustomize.py"
        )
    out_path.write_text(content, encoding="utf-8")
    HELM_VALUES.write_text(mounts_content, encoding="utf-8")
    print(
        f"Wrote {out_path.relative_to(REPO_ROOT)} "
        f"({len(yaml_files)} files under {FILES_DIR.relative_to(REPO_ROOT)})"
    )
    print(f"Wrote {HELM_VALUES.relative_to(REPO_ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Render ops-config Kustomize for Argo CD"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated output would change",
    )
    args = parser.parse_args()
    render(check=args.check)


if __name__ == "__main__":
    main()
